//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_CMSCONTENT
    {
        public int MENUID { get; set; }
        public short CONTENTTYPE { get; set; }
        public byte[] CONTENTDETAIL { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    
        public virtual MWP_CMSMENU MWP_CMSMENU { get; set; }
    }
}
