//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_DLCONTENT
    {
        public decimal DLCONTENTID { get; set; }
        public decimal DLCATEGORYID { get; set; }
        public string DLCONTENTTITLE { get; set; }
        public string DLCONTENTDESCRIPTION { get; set; }
        public short ISPUBLISHED { get; set; }
        public decimal DLSORTORDER { get; set; }
        public string TEMP_ORIGIN { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    }
}
