//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_MCSPEECHES
    {
        public decimal SPEECHID { get; set; }
        public string SPEECHTITLE { get; set; }
        public System.DateTime SPEECHTIMESTAMP { get; set; }
        public string SPEECHCONTENT { get; set; }
        public short ISPUBLISHED { get; set; }
    }
}
