//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_THREADABLEEVENT
    {
        public decimal THREADID { get; set; }
        public decimal EVENTCATEGORYID { get; set; }
        public System.DateTime EVENTSTARTTIME { get; set; }
        public System.DateTime EVENTENDTIME { get; set; }
        public string EVENTURL { get; set; }
        public System.DateTime EVENTPOSTSTARTTIME { get; set; }
        public System.DateTime EVENTPOSTENDTIME { get; set; }
    }
}
