//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_VIDEO
    {
        public decimal VIDEOID { get; set; }
        public string VIDEOTITLE { get; set; }
        public string VIDEODESCRIPTION { get; set; }
        public System.DateTime VIDEOTIMESTAMP { get; set; }
        public short ISPUBLISHED { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    }
}
