//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_THREADABLEREPLY
    {
        public decimal REPLYID { get; set; }
        public decimal THREADID { get; set; }
        public string REPLYAUTHOR { get; set; }
        public System.DateTime REPLYTIMESTAMP { get; set; }
        public string REPLYCONTENT { get; set; }
        public decimal REPLYPARENT { get; set; }
    }
}
