//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_CMSBANNER
    {
        public decimal BANNERID { get; set; }
        public System.DateTime BANNERSTARTTIME { get; set; }
        public System.DateTime BANNERENDTIME { get; set; }
        public string BANNERTITLE { get; set; }
        public short BANNERTYPE { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    }
}
