//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_FAQ
    {
        public decimal FAQ_ID { get; set; }
        public decimal FAQ_CATEGORY_ID { get; set; }
        public string FAQ_QUESTION { get; set; }
        public string FAQ_ANSWER { get; set; }
        public short FAQ_ISPUBLISHED { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    
        public virtual MWP_FAQCATEGORY MWP_FAQCATEGORY { get; set; }
    }
}
