//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_MCGALLERYIMAGE
    {
        public decimal IMAGEID { get; set; }
        public decimal ALBUMID { get; set; }
        public string CAPTION { get; set; }
        public byte[] CONTENT { get; set; }
        public short ISPUBLISHED { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
        public string TEMP_FILE { get; set; }
    }
}
