//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_MCGALLERYALBUM
    {
        public decimal ALBUMID { get; set; }
        public string ALBUMNAME { get; set; }
        public System.DateTime ALBUMEVENTDATE { get; set; }
        public decimal ALBUMTHUMBNAIL { get; set; }
        public short ISPUBLISHED { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
    }
}
