//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_THREADABLEEVENTCAT
    {
        public decimal EVENTCATEGORYID { get; set; }
        public string EVENTCATEGORYNAME { get; set; }
        public string EVENTCATEGORYDESC { get; set; }
    }
}
