//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWP_CMSMENU
    {
        public MWP_CMSMENU()
        {
            this.MWP_CMSCONTENT = new HashSet<MWP_CMSCONTENT>();
            this.MWP_CMSMENU1 = new HashSet<MWP_CMSMENU>();
        }
    
        public int MENUID { get; set; }
        public int MENUPARENT { get; set; }
        public string MENULABEL { get; set; }
        public int MENUORDER { get; set; }
        public short ISPUBLISHED { get; set; }
        public Nullable<decimal> TEMP_ID { get; set; }
        public Nullable<decimal> TEMP_CONTENT_ID { get; set; }
        public Nullable<decimal> TEMP_LEVEL { get; set; }
    
        public virtual ICollection<MWP_CMSCONTENT> MWP_CMSCONTENT { get; set; }
        public virtual ICollection<MWP_CMSMENU> MWP_CMSMENU1 { get; set; }
        public virtual MWP_CMSMENU MWP_CMSMENU2 { get; set; }
    }
}
