//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MWPEntities : DbContext
    {
        public MWPEntities()
            : base("name=MWPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MWP_CMSBANNER> MWP_CMSBANNER { get; set; }
        public DbSet<MWP_CMSBANNERCONTENT> MWP_CMSBANNERCONTENT { get; set; }
        public DbSet<MWP_CMSCONTENT> MWP_CMSCONTENT { get; set; }
        public DbSet<MWP_CMSMENU> MWP_CMSMENU { get; set; }
        public DbSet<MWP_DLCATEGORY> MWP_DLCATEGORY { get; set; }
        public DbSet<MWP_DLCONTENT> MWP_DLCONTENT { get; set; }
        public DbSet<MWP_DLCONTENTFILE> MWP_DLCONTENTFILE { get; set; }
        public DbSet<MWP_FAQ> MWP_FAQ { get; set; }
        public DbSet<MWP_FAQCATEGORY> MWP_FAQCATEGORY { get; set; }
        public DbSet<MWP_IWANTTO> MWP_IWANTTO { get; set; }
        public DbSet<MWP_IWANTTODTL> MWP_IWANTTODTL { get; set; }
        public DbSet<MWP_MCGALLERYALBUM> MWP_MCGALLERYALBUM { get; set; }
        public DbSet<MWP_MCGALLERYIMAGE> MWP_MCGALLERYIMAGE { get; set; }
        public DbSet<MWP_MCPHOTORELEASE> MWP_MCPHOTORELEASE { get; set; }
        public DbSet<MWP_MCPHOTORELEASEIMG> MWP_MCPHOTORELEASEIMG { get; set; }
        public DbSet<MWP_MCSPEECHES> MWP_MCSPEECHES { get; set; }
        public DbSet<MWP_THREADABLE> MWP_THREADABLE { get; set; }
        public DbSet<MWP_THREADABLEEVENT> MWP_THREADABLEEVENT { get; set; }
        public DbSet<MWP_THREADABLEEVENTCAT> MWP_THREADABLEEVENTCAT { get; set; }
        public DbSet<MWP_THREADABLENEWS> MWP_THREADABLENEWS { get; set; }
        public DbSet<MWP_THREADABLEREPLY> MWP_THREADABLEREPLY { get; set; }
        public DbSet<MWP_THREADCATEGORY> MWP_THREADCATEGORY { get; set; }
        public DbSet<MWP_VIDEO> MWP_VIDEO { get; set; }
        public DbSet<MWP_VIDEOFILE> MWP_VIDEOFILE { get; set; }
        public DbSet<TEST_IMAGE_CONVERT> TEST_IMAGE_CONVERT { get; set; }
    }
}
