//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertToBase64
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_IMAGE_CONVERT
    {
        public int ID { get; set; }
        public byte[] DATA_IMAGE { get; set; }
        public string TEMP_PATH { get; set; }
    }
}
